### GET all products
GET http://localhost:7904/products

### GET all products with this author OR title
GET http://localhost:7904/products?author=Steve&title=hello

### GET all products with this title
GET http://localhost:7904/products?author=Ste

### POST A PRODUCT
POST http://localhost:7904/products
Content-Type: application/json 

{
  "title": "Marsupilami - Die Schmetterlingsjäger",
  "author": "Franquin Batem & Yann",
  "price": 200,
  "picture": [
    "http://localhost:7904/pictures/Marsupilami24_0.jpg",
    "http://localhost:7904/pictures/Marsupilami24_1.jpg",
    "http://localhost:7904/pictures/Marsupilami24_2.jpg"
  ],
  "currency": "SEK",
  "genre": "fiction",
  "startage": 7,
  "quantity": 20,
  "description": "Ein Forscherteam kommt in den palumbianischen Dschungel, um dort einen seltenen Schmetterling zu suchen, der bevorzugt in den Wipfeln der Bäume lebt und seine Eier gerne auf die Nester von Marsupilamis ablegt. Als sich merkwürdige Zwischenfälle häufen, kommt ihnen ein schwerer Verdacht: Ein Saboteur hat sich eingeschlichen! Ab sofort findet eine Doppejagd auf den Schurken und den Schmetterling statt!",
  "language": "deutsch",
  "form": "hardcover",
  "quality": 
} 



### POST A USER 
POST http://localhost:7904/users
Content-Type: application/json 

{
    "_id": "silvia",
"shippingAdress": {
  "street": "Treegreen 8",
  "postalCode": 1010,
  "city": "Waterland",
  "country": "Seeweedy",
  "datestamp": "Wed Mar 19 2022 18:03:09 GMT-0500 (EST)"
  },
"role": "customer"  
}

### POST AN ARTICLE IN THE CART
POST http://localhost:7904/shopping-cart
Content-Type: application/json 

{
  "customersId": "guest",
  "article": {  
    "articleId": "TOBEINSERTEDFROMTHEOBJEC OR STRING?",
    "title": "Marsupilami - Die Schmetterlingsjäger",
    "author": "Franquin Batem & Yann",
    "price": 200,
    "picture": "http://localhost:7904/pictures/Marsupilami24_0.jpg",
    "currency": "SEK"},
  "quantity": 2,
  "datestamp": "Wed Mar 23 2022 18:03:09 GMT-0500 (EST)"
} 

### POST FOR LOGIN 
POST http://localhost:7904/users/login
Content-Type: application/json 

{
  "username": "alessia.zapalotti@gmail.com",
  "password": "AlessiaIstSchlauer"
}
