### GET all products
GET http://localhost:7904/products


### POST A PRODUCT
POST http://localhost:7904/products
Content-Type: application/json 

{
  "title": "Wenn ich gross bin, werde ich Astromaus",
  "author": "Steve Smallmann",
  "price": 120,
  "picture": {
    "frontpicture": "http://localhost:7904/pictures/Astromaus.jpg",
    "firstSidepicture": "http://localhost:7904/pictures/Astromaus1.jpg",
    "backpicture": "http://localhost:7904/pictures/Astromaus2.jpg"
  },
  "currency": "SEK",
  "genre": "fiction",
  "startage": 0,
  "quantity": 10 
} 



### POST A USER 
POST http://localhost:7904/products
Content-Type: application/json 

{
    "_id": "alessia.zapalotti@gmail.com",
"shippingAdress": {
  "street": "Treegreen 8",
  "postalCode": 1010,
  "city": "Waterland",
  "country": "Seeweedy",
  "datestamp": "Wed Mar 19 2022 18:03:09 GMT-0500 (EST)"
  },
"role": "customer"  
}