### GET all products
GET http://localhost:7904/products

### GET all products with this author OR title
GET http://localhost:7904/products?author=Steve&title=hello

### GET all products with this title
GET http://localhost:7904/products?author=Ste

### POST A PRODUCT
POST http://localhost:7904/products
Content-Type: application/json 

{
  "title": "Das Osmanische Reich 1300-1922",
  "author": "GEO EPOCHE",
  "price": 110,
  "picture": [
    "http://localhost:7904/pictures/IMG-1920.jpg",
    "http://localhost:7904/pictures/IMG-1921.jpg",
    "http://localhost:7904/pictures/IMG-1922.jpg"
  ],
  "currency": "SEK",
  "genre": "magazine",
  "startage": 9,
  "quantity": 30,
  "description": "Sultane, Wesire, Paschas: Geschichte eines islamischen Imperiums",
  "language": "deutsch",
  "form": "paperback",
  "quality": "good"
} 


### POST A USER 
POST http://localhost:7904/users
Content-Type: application/json 

{
    "_id": "silvia",
"shippingAdress": {
  "street": "Treegreen 8",
  "postalCode": 1010,
  "city": "Waterland",
  "country": "Seeweedy",
  "datestamp": "Wed Mar 19 2022 18:03:09 GMT-0500 (EST)"
  },
"role": "customer"  
}

### POST AN ARTICLE IN THE CART
POST http://localhost:7904/shopping-cart
Content-Type: application/json 

{
  "customersId": "guest",
  "article": {  
    "articleId": "TOBEINSERTEDFROMTHEOBJEC OR STRING?",
    "title": "Marsupilami - Die Schmetterlingsjäger",
    "author": "Franquin Batem & Yann",
    "price": 200,
    "picture": "http://localhost:7904/pictures/Marsupilami24_0.jpg",
    "currency": "SEK"},
  "quantity": 2,
  "datestamp": "Wed Mar 23 2022 18:03:09 GMT-0500 (EST)"
} 

### POST FOR LOGIN 
POST http://localhost:7904/users/login
Content-Type: application/json 

{
  "username": "alessia.zapalotti@gmail.com",
  "password": "AlessiaIstSchlauer"
}

### GET THE SHOPPING-CART
GET http://localhost:7904/shopping-cart/12x7fgh44


### Post a product to the shopping-cart
POST http://localhost:7904/shopping-cart/article
Content-Type: application/json
     
{
  "productId": "623e3e6f829ee9c8e9da95ea",
  "token": "d5p2i9l6v9o0"
}